# Generated by Django 5.0.4 on 2024-10-03 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0002_clientes_tipositensadicionais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='codusuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cg.usuarios'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='razaosocial',
            field=models.TextField(default='Razao', max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='codcliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cg.clientes'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.TextField(default='CNPJ', max_length=1),
        ),
        migrations.AlterField(
            model_name='itensadicionais',
            name='codcontrato',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_cg.contrato'),
        ),
        migrations.AlterField(
            model_name='itensadicionais',
            name='codtipoitem',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_cg.tipositensadicionais'),
        ),
    ]
