# Generated by Django 5.0.4 on 2024-10-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0005_rename_telefoni_teste_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='teste',
            field=models.TextField(default='teste_criando_nova_coluna'),
        ),
    ]
