# Generated by Django 5.0.4 on 2024-10-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0006_teste_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensadicionais',
            name='nome',
            field=models.TextField(default='Item', max_length=100),
        ),
    ]
