# Generated by Django 5.0.4 on 2024-10-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0007_itensadicionais_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensadicionais',
            name='dtatualiz',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
