# Generated by Django 5.0.4 on 2024-10-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0009_visualizar_contratos_clientes_qtdcontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='dtcriacao',
            field=models.DateField(null=True),
        ),
    ]
