# Generated by Django 5.2.5 on 2025-08-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0009_visualizar_contratos_usuarios_permissoes'),
        ('app_cg', '0010_clientes_dtcriacao'),
    ]

    operations = [
    ]
