# Generated by Django 5.2.5 on 2025-08-14 03:12

import app_cg.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0011_merge_20250814_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codtipoitens_itensadicionais',
            fields=[
                ('codtipoitem', models.IntegerField()),
                ('nome', models.TextField(default='Item', max_length=100)),
                ('codcontrato_id', models.IntegerField()),
                ('codvtipoitens', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'v_codtipoitem_itensadicionais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('codtemplate', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(default='Template', max_length=100)),
                ('descricao', models.TextField(default='', max_length=255)),
                ('template', models.FileField(blank=True, null=True, upload_to='templates/', validators=[app_cg.models.validar_extensao_docx])),
                ('dtatualiz', models.TextField(max_length=10, null=True)),
                ('status', models.IntegerField(null=True)),
                ('codempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cg.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('codcontrato', models.AutoField(primary_key=True, serialize=False)),
                ('contrato', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('contrato_json', models.JSONField(blank=True, null=True)),
                ('status', models.IntegerField(null=True)),
                ('dtatualiz', models.TextField(max_length=10, null=True)),
                ('codempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cg.empresas')),
                ('codtemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cg.templates')),
            ],
        ),
        migrations.CreateModel(
            name='Variaveis',
            fields=[
                ('codvariavel', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(default='', max_length=100)),
                ('descricao', models.TextField(default='', max_length=255)),
                ('tipo', models.IntegerField(null=True)),
                ('dtatualiz', models.TextField(max_length=10, null=True)),
                ('status', models.IntegerField(null=True)),
                ('codtemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cg.templates')),
            ],
        ),
    ]
