# Generated by Django 5.2.5 on 2025-08-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0012_codtipoitens_itensadicionais_templates_contratos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variaveis',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='variaveis',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='variaveis',
            name='tipo',
        ),
        migrations.AddField(
            model_name='variaveis',
            name='variaveis',
            field=models.JSONField(null=True),
        ),
    ]
