# Generated by Django 5.2.5 on 2025-08-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0013_remove_variaveis_descricao_remove_variaveis_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='dtatualiz',
            field=models.TextField(max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='dtatualiz',
            field=models.TextField(max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='itensadicionais',
            name='dtatualiz',
            field=models.TextField(max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='templates',
            name='dtatualiz',
            field=models.TextField(max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='variaveis',
            name='dtatualiz',
            field=models.TextField(max_length=19, null=True),
        ),
    ]
