# Generated by Django 5.2.5 on 2025-09-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0014_alter_contrato_dtatualiz_alter_contratos_dtatualiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='template',
        ),
        migrations.AddField(
            model_name='templates',
            name='template_url',
            field=models.TextField(default='Template', max_length=100),
        ),
    ]
