# Generated by Django 5.2.5 on 2025-09-06 12:16

import app_cg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0015_remove_templates_template_templates_template_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='template_url',
        ),
        migrations.AddField(
            model_name='templates',
            name='template',
            field=models.FileField(blank=True, null=True, upload_to='templates/', validators=[app_cg.models.validar_extensao_docx]),
        ),
    ]
