# Generated by Django 5.2.5 on 2025-09-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0016_remove_templates_template_url_templates_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='template',
        ),
        migrations.AddField(
            model_name='templates',
            name='template_url',
            field=models.TextField(default='Template'),
        ),
    ]
