# Generated by Django 5.2.5 on 2025-09-13 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0017_remove_templates_template_templates_template_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='codempresa',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='contrato',
        ),
        migrations.AddField(
            model_name='contratos',
            name='codusuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cg.usuarios'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='contrato_url',
            field=models.TextField(default='Contrato'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='dtatualiz',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='templates',
            name='dtatualiz',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='variaveis',
            name='dtatualiz',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
