# Generated by Django 5.2.5 on 2025-09-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0017_remove_templates_template_templates_template_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='dois_fatores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='permissoes',
            field=models.CharField(choices=[('admin', 'Admin'), ('gestor', 'Gestor'), ('colaborador', 'Colaborador')], default='colaborador', max_length=20),
        ),
    ]
