# Generated by Django 5.2.5 on 2025-09-19 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0018_remove_contratos_codempresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='codempresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_cg.empresas'),
            preserve_default=False,
        ),
    ]
