# Generated by Django 5.2.5 on 2025-09-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0019_contratos_codempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='nome_arquivo',
            field=models.TextField(default=''),
        ),
    ]
