# Generated by Django 5.2.5 on 2025-09-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0020_contratos_nome_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='dtatualiz',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
