# Generated by Django 5.2.5 on 2025-09-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0018_usuarios_dois_fatores_usuarios_otp_secret_and_more'),
        ('app_cg', '0021_alter_contratos_dtatualiz'),
    ]

    operations = [
    ]
