# Generated by Django 5.2.5 on 2025-09-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0022_merge_20250920_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='dtatualiz',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variaveis',
            name='dtatualiz',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
