# Generated by Django 5.2.5 on 2025-10-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0023_alter_templates_dtatualiz_alter_variaveis_dtatualiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='utiliza_dois_fatores',
            field=models.BooleanField(default=True),
        ),
    ]
