# Generated by Django 5.2.5 on 2025-11-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0024_usuarios_utiliza_dois_fatores'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Templates_codnomedtatualiz',
            fields=[
                ('codtemplate', models.AutoField(primary_key=True, serialize=False)),
                ('codempresa', models.IntegerField(null=True)),
                ('nome', models.TextField(default='Template', max_length=100)),
                ('dtatualiz', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'VIEW_TEMPLATES_CODNOMEDTATUALIZ',
                'managed': False,
            },
        ),
    ]
