# Generated by Django 5.2.5 on 2025-11-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0025_v_templates_codnomedtatualiz'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='v_templates_codnomedtatualiz',
            table='v_codtipoitem_itensadicionais',
        ),
    ]
