# Generated by Django 5.2.5 on 2025-11-19 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cg', '0026_alter_v_templates_codnomedtatualiz_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='v_templates_codnomedtatualiz',
            table='view_templates_codnomedtatualiz',
        ),
    ]
