"""
Django settings for contract_generator project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path# settings.py
import dj_database_url
from decouple import config
from dotenv import load_dotenv
load_dotenv()



#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PWA_SERVICE_WORKER_PATH = os.path.join (BASE_DIR, 'app_cg/static/js', 'service-worker.js')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k*^0a0u91jjt^r01#tq6)1eq!ug=#4w+!jytx*hxmf3=wtnt5x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.vercel.app', 'now.sh', '127.0.0.1', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pwa',
    'app_cg',
    'storages'
]
#Conexão com a nuvem da AWS
    # Documentação django-storages: https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
    
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN")
AWS_QUERYSTRING_AUTH = False
# AWS_DEFAULT_ACL = 'public-read'

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage"
    },
    "OPTIONS": {
        "location": "Gerador_De_Contratos",
        "bucket_name": AWS_STORAGE_BUCKET_NAME,
        "region_name": AWS_S3_REGION_NAME,
        "access_key": AWS_ACCESS_KEY_ID,
        "secret_key": AWS_SECRET_ACCESS_KEY,
        # "default_acl": AWS_DEFAULT_ACL,
        # "custom_domain": AWS_S3_CUSTOM_DOMAIN, # Descomente se usar um domínio customizado
        "file_overwrite": False,
        },
    # A configuração 'staticfiles' é para os arquivos estáticos (collectstatic)
    "staticfiles": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "location": "static", # Caminho opcional dentro do bucket
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "region_name": AWS_S3_REGION_NAME,
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            # "default_acl": AWS_DEFAULT_ACL,
            # "custom_domain": AWS_S3_CUSTOM_DOMAIN, # Descomente se usar um domínio customizado
            "file_overwrite": True, # Geralmente é True para arquivos estáticos
        },
    },
}

# AWS_S3_SIGNATURE_VERSION = "s3v4"
# AWS_S3_FILE_OVERWRITE = False
# AWS_DEFAULT_ACL = None
# AWS_S3_VERITY = True
# AWS_LOCATION = "GeradorDeContratos"
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app_cg.middleware.DatabaseErrorMiddleware',
]

ROOT_URLCONF = 'contract_generator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'app_cg', 'templates')],  # Este campo pode estar vazio
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'contract_generator.wsgi.application'


DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL')
    )
} # --> Necessário deixar essa constante, pois a Vercel irá ignorar o valor dessa constante, pois o valor 
#   --> está configurado no arquivo .env do projeto, e o mesmo está no gitIgnore, ou seja, a Vercel 
#   --> Irá utilizar a conexão que está configurada nas variáveis de ambiente da Vercel, que é a conexão 
#   --> do banco de dados de Produção, de forma que, em ambiente de desenvolvimento, local, será utilizada
#   --> conexão com o banco de homologação, e depois que é feito deployment na Vercel, será utilizado banco em produção


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'  # URL prefix para arquivos estáticos
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'app_cg', 'static')]  # Local onde os arquivos estáticos estão armazenados
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PWA_APP_NAME = 'ContractGenerator'
PWA_APP_DESCRIPTION = "ContractGenerator Django PWA"
PWA_APP_THEME_COLOR = '#000000'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    # {
    #     'src': '/pwa-logo.png',
    #     'sizes': '160x103'
    # },
    # {
    #     'src': '/pwa-logo.png',
    #     'sizes': '192x192'
    # },
    # {
    #     'src': '/pwa-logo.png',
    #     'sizes': '512x512'
    # }
    {
        'src': 'https://raw.githubusercontent.com/HenriqueTorresA/ContractGenerator/refs/heads/henr/app_cg/static/images/stardm-160x103.png',
        'sizes': '160x103'
    },
    {
        'src': 'https://raw.githubusercontent.com/HenriqueTorresA/ContractGenerator/refs/heads/henr/app_cg/static/images/stardm-192x192.PNG',
        'sizes': '192x192'
    },
    {
        'src': 'https://raw.githubusercontent.com/HenriqueTorresA/ContractGenerator/refs/heads/henr/app_cg/static/images/stardm-512x512.PNG',
        'sizes': '512x512'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': 'https://raw.githubusercontent.com/HenriqueTorresA/ContractGenerator/refs/heads/henr/app_cg/static/images/stardm-160x103.png',
        'sizes': '160x103'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': 'https://raw.githubusercontent.com/HenriqueTorresA/ContractGenerator/refs/heads/henr/app_cg/static/images/contract-4085336_1280.jpeg',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'


# Tempo de expiração da sessão em segundos (30 minutos = 30 * 60 segundos)
SESSION_COOKIE_AGE = 30 * 60

# Define que a sessão expira quando o usuário fechar o navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Define que a sessão será renovada a cada nova requisição dentro do período de 30 minutos
SESSION_SAVE_EVERY_REQUEST = True

